output "id" {
  description = "The ID of the Container App Environment"
  value       = azurerm_container_app_environment.cae.id
}

output "default_domain" {
  description = "The default, publicly resolvable, name of this Container App Environment.  This value is generated by the service to be globally unique."
  value       = azurerm_container_app_environment.cae.default_domain
}

output "docker_bridge_cidr" {
  description = "The network addressing in which the Container Apps in this Container App Environment will reside in CIDR notation.  This property only has a value when infrastructure_subnet_id is configured and will be a value within the CIDR of the Subnet."
  value       = azurerm_container_app_environment.cae.docker_bridge_cidr
}

output "platform_reserved_cidr" {
  description = "The IP range, in CIDR notation, that is reserved for environment infrastructure IP addresses.  This property only has a value when infrastructure_subnet_id is configured and will be a value within the CIDR of the Subnet."
  value       = azurerm_container_app_environment.cae.platform_reserved_cidr
}

output "platform_reserved_dns_ip_address" {
  description = "The IP address from the IP range defined by platform_reserved_cidr that is reserved for the internal DNS server.  This property only has a value when infrastructure_subnet_id is configured and will be a value within the CIDR of the Subnet."
  value       = azurerm_container_app_environment.cae.platform_reserved_dns_ip_address
}

output "static_ip_address" {
  description = "The Static IP address of the Environment.  This will be a Public IP unless internal_load_balancer_enabled is set to true, in which case an IP in the Internal Subnet will be reserved."
  value       = azurerm_container_app_environment.cae.static_ip_address
}