parameters:
- name: armTenantId
  type: string
  default: $(ARM_TENANT_ID)
- name: armSubscriptionId
  type: string
  default: $(ARM_SUBSCRIPTION_ID)
- name: armClientId
  type: string
  default: $(ARM_CLIENT_ID)
- name: armClientSecret
  type: string
  default: $(ARM_CLIENT_SECRET)
- name: keyVaultName
  type: string
  default: ''

steps:
- task: Bash@3
  displayName: "Remove Agent IP (Key Vault)"
  condition: always()
  inputs:
    targetType: 'inline'
    script: |
      # Authenticate with Azure using existing environment variables
      az login \
        --service-principal -u ${{ parameters.armClientId }} -p ${{ parameters.armClientSecret }} \
        --tenant ${{ parameters.armTenantId }} \
        --output none

      # Set the susbscription
      az account set --subscription ${{ parameters.armSubscriptionId }}

      # Remove Agent IP address from Key Vault firewall rules
      az keyvault network-rule remove \
        --name ${{ parameters.keyVaultName }} \
        --ip-address "$(agent_ip/32" \
        --output none
      
      # Output the agent's IP address
      echo "Removed agent IP: $agent_ip from the firewall rule"
